extends: airbnb

env:
  browser: true
  mocha: true

plugins:
  - react-hooks

rules:
  no-alert: 0
  quote-props: 0
  camelcase: 0
  comma-dangle: 0
  no-bitwise: 0
  no-mixed-operators: 0
  semi: [2, always]
  prefer-promise-reject-errors: 0
  no-underscore-dangle: 0
  no-param-reassign: [error, { props: false }]
  no-plusplus: 0
  max-classes-per-file: 0
  object-curly-spacing: [2, always]
  arrow-parens: [2, as-needed, { requireForBlockBody: true }]
  react/sort-comp: 0
  react/no-danger: 0
  react/forbid-prop-types: 0
  react/jsx-filename-extension: 0
  react/destructuring-assignment: 0
  react/static-property-placement: 0
  react/state-in-constructor: 0
  react/jsx-props-no-spreading: 0
  react/jsx-no-target-blank: 0
  react/jsx-fragments: 0
  jsx-a11y/href-no-hash: 0
  jsx-a11y/anchor-is-valid: 0
  jsx-a11y/label-has-for: 0
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/control-has-associated-label: 0
  jsx-a11y/click-events-have-key-events: 0
  react-hooks/rules-of-hooks: 2

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
